language: go
go: master
before_script:
  - echo 'Checking code quality issues.'
  - go vet ./...
  - echo 'Checking that gofmt was used.'
  - diff -u <(echo -n) <(gofmt -d .)
  - echo 'Checking tidiness of go mod.'
  - go mod tidy
  - test -z "$(git status --porcelain)"
script:
  - echo 'Running tests.'
  - go test -v ./...
